- graphql_codegen/README.md
Fix typo `GQLFQueryFetchPersion`
Make a bit clearer on basic usage
> fix: typo `GQLFQueryFetchPersion` in `README.md`

- graphql_codegen/CHANGELOG.md
- graphql_codegen/example/lib/main.graphql.g.dart
- graphql_codegen/lib/graphql_codegen.dart
- graphql_codegen/lib/src/transform/transform_visitor.dart
- graphql_codegen/pubspec.lock
- graphql_codegen/pubspec.yaml
- graphql_codegen/test/assets/add_typenames/options.json
- graphql_codegen/test/assets/add_typenames/schema.graphql
- graphql_codegen/test/assets/add_typenames/schema.graphql.dart
By setting the `addTypename` configuration, the `__typename` introspection will be added to all selection sets.
> feat: Add addTypename transformation

- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen_config/CHANGELOG.md
- packages/graphql_codegen_config/lib/config.dart
- packages/graphql_codegen_config/lib/config.g.dart
- packages/graphql_codegen_config/pubspec.yaml
- packages/graphql_codegen_config/test/config_parsing_test.dart
Add new options:
* `addTypenameExcludedPaths`: This'll allow us to specify which query paths shouldn't have added any typename.
* `assetsPath`: A glob specifying where to look for assets
> feat: Add new config options

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
* Allow for customisable asset path through the `assetPath` config option.
> feat: Add customizable asset path

- melos.yaml
- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/fragments.graphql.dart
- packages/graphql_codegen/example/lib/main.dart
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql_flutter.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_required_arguments/document.graphql.dart
Use the newly introduced parserFn through options.
> feat: Use new parserfn

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql_flutter.dart
- packages/graphql_codegen/lib/src/printer/clients/utils.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_subscription/options.json
- packages/graphql_codegen/test/assets/graphql_flutter_client_subscription/schema.graphql
- packages/graphql_codegen/test/assets/graphql_flutter_client_subscription/schema.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_subscription/schema.graphql.g.dart
> feat: Support subscriptions in client

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/header/options.json
- packages/graphql_codegen/test/assets/header/schema.graphql
- packages/graphql_codegen/test/assets/header/schema.graphql.dart
- packages/graphql_codegen/test/transform_test.dart
- packages/graphql_codegen_config/CHANGELOG.md
- packages/graphql_codegen_config/lib/config.dart
- packages/graphql_codegen_config/lib/config.g.dart
- packages/graphql_codegen_config/pubspec.yaml
- packages/graphql_codegen_config/test/config_parsing_test.dart
Allow specifying headers for generated files through the `generatedFileHeader` option.
> feat: Support generated file headers

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
> version: Bump version

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql_flutter.dart
- packages/graphql_codegen/lib/src/printer/utils.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_subscription/schema.graphql.dart
Following zino-hofmann/graphql-flutter/pull/1034, we can now generate hooks.
> feat: Support hooks

- packages/graphql_codegen/pubspec.yaml
> version: 0.7.0-beta.2

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql_flutter.dart
- packages/graphql_codegen/lib/src/printer/utils.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
This change will make the options optional when possible.
> feat: Improve hooks options

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/build.yaml
- packages/graphql_codegen/example/lib/fragments.graphql
- packages/graphql_codegen/example/lib/fragments.graphql.dart
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/example/lib/main.graphql.g.dart
- packages/graphql_codegen/example/lib/scalars.dart
- packages/graphql_codegen/example/lib/schema.graphql
- packages/graphql_codegen/lib/src/printer/context.dart
- packages/graphql_codegen/lib/src/printer/printer.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/scalars/document.graphql
- packages/graphql_codegen/test/assets/scalars/document.graphql.dart
- packages/graphql_codegen/test/assets/scalars/document.graphql.g.dart
This PR improves scalar parsing by handling nullable and list values.
> feat: Improve scalar parsing

- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen_config/CHANGELOG.md
- packages/graphql_codegen_config/lib/config.dart
- packages/graphql_codegen_config/lib/config.g.dart
- packages/graphql_codegen_config/pubspec.yaml
> feat: Add scopes config

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/fragments.graphql.dart
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/lib/src/printer/printer.dart
- packages/graphql_codegen/lib/src/visitor/context_visitor.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/fragment_variables/document.graphql
- packages/graphql_codegen/test/assets/fragment_variables/document.graphql.dart
- packages/graphql_codegen/test/assets/fragment_variables/document.graphql.g.dart
- packages/graphql_codegen/test/assets/graphql_client/document.graphql
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.g.dart
This'll infer the variables for a fragment.
> feat: Generate fragment variables

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document.graphql
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document.graphql.g.dart
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/options.json
Reduce number of cache methods.
> fix: Don't generate cache methods for nested fragments

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/utils.dart
This PR fixes bad naming of non-const global variable.
> fix: Bad naming

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/fragments.graphql.dart
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/lib/src/printer/printer.dart
- packages/graphql_codegen/lib/src/printer/utils.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/add_typenames/schema.graphql.dart
- packages/graphql_codegen/test/assets/first_test/a.graphql.dart
- packages/graphql_codegen/test/assets/first_test/fragments.graphql.dart
- packages/graphql_codegen/test/assets/fragment_imports/document1.graphql.dart
- packages/graphql_codegen/test/assets/fragment_imports/document2.graphql.dart
- packages/graphql_codegen/test/assets/fragment_override/document.graphql.dart
- packages/graphql_codegen/test/assets/fragment_variables/document.graphql.dart
- packages/graphql_codegen/test/assets/fragments_and_loose_type_requirements/document.graphql.dart
- packages/graphql_codegen/test/assets/fragments_inheritence/document.graphql.dart
- packages/graphql_codegen/test/assets/fragments_nested_data/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document.graphql
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document.graphql.g.dart
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document2.graphql
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document2.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client_nested_fragments/document2.graphql.g.dart
- packages/graphql_codegen/test/assets/interface_and_fragments/query.graphql.dart
- packages/graphql_codegen/test/assets/lots_of_fragments/document.graphql.dart
- packages/graphql_codegen/test/assets/multiple_interfaces/document.graphql.dart
- packages/graphql_codegen/test/assets/nested_inline_and_fragment_spread/document.graphql.dart
Create new `DocumentNode` for fragments and import other fragment definitions.
> fix: Support nested fragments

- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen_config/CHANGELOG.md
- packages/graphql_codegen_config/lib/config.dart
- packages/graphql_codegen_config/lib/config.g.dart
- packages/graphql_codegen_config/pubspec.yaml
This PR adds a new option allowing us to set `includeIfNull` on input serializers.
> feat: Include if null on input

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/README.md
- packages/graphql_codegen/lib/src/printer/printer.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/include_if_null_input/document.graphql
- packages/graphql_codegen/test/assets/include_if_null_input/document.graphql.dart
- packages/graphql_codegen/test/assets/include_if_null_input/document.graphql.g.dart
- packages/graphql_codegen/test/assets/include_if_null_input/options.json
This PR uses the newly created `includeIfNullOnInput` option.
> feat: Enable `includeIfNullOnInput` option

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
> release: v0.7.0

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/README.md
- packages/graphql_codegen/pubspec.yaml
> docs: Update README.md

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
> release: Release v0.8.0

- packages/graphql_codegen/test/assets/fragment_variables_2/options.json
- packages/graphql_codegen/test/assets/fragment_variables_2/schema.graphql
- packages/graphql_codegen/test/assets/fragment_variables_2/schema.graphql.dart
- packages/graphql_codegen/test/assets/fragment_variables_2/schema.graphql.g.dart
> feat: Add fragment variables test

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/lib/src/visitor/context_visitor.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/fragment_enum_variables/schema.graphql
- packages/graphql_codegen/test/assets/fragment_enum_variables/schema.graphql.dart
- packages/graphql_codegen/test/assets/fragment_enum_variables/schema.graphql.g.dart
> fix: Bad state on enum variables

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/lib/src/printer/printer.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/duplicate_names/document.graphql.dart
- packages/graphql_codegen/test/assets/fragment_enum_variables/schema.graphql.dart
- packages/graphql_codegen/test/assets/fragment_variables/document.graphql.dart
- packages/graphql_codegen/test/assets/fragment_variables_2/schema.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_subscription/schema.graphql.dart
- packages/graphql_codegen/test/assets/include_if_null_input/document.graphql.dart
- packages/graphql_codegen/test/assets/input/input.graphql.dart
- packages/graphql_codegen/test/assets/variables/schema.graphql.dart
- packages/graphql_codegen/test/assets/variables/variables.graphql.dart
Adds `copyWith` on inputs and variables.
> feat: add copy with on input

- packages/graphql_codegen/README.md
> docs: Update README examples

- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen_config/CHANGELOG.md
- packages/graphql_codegen_config/lib/config.dart
- packages/graphql_codegen_config/lib/config.g.dart
- packages/graphql_codegen_config/pubspec.yaml
Adds new `extraKeywords` option allowing users to define their own keywords (part of #96).
> feat: custom keywords

- packages/graphql_codegen/README.md
> docs: Add inline fragment docs

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
> release: v0.9.0

- packages/graphql_codegen/pubspec.yaml
> release: 0.10.0-beta.3

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.yaml
This diff ensures that we're using posix style paths when resolving the output dir.
> fix: Path context

- .github/workflows/check_pr.yml
Conventional PR doesn't work on 3rd party PRs
> fix: Conventional PR

- packages/graphql_codegen/README.md
Just added the options table with links to the sections where the options are discussed. Some of the options I still don't totally understand like `extraKeywords` so maybe you could word them better.
I added the options in order of what I assumed would be the most commonly used....and then reordered the sections. Didn't change anything in the actual sections
Also I updated the `Installation` section have a bit more detail about the dependencies
> docs: Add options table and reshuffle sections

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
> release: v0.10.0

- packages/graphql_codegen/README.md
Mainly because I screwed up the installation command
> docs: Fix typos

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/operation_name_collision/mutation.graphql
- packages/graphql_codegen/test/assets/operation_name_collision/mutation.graphql.dart
- packages/graphql_codegen/test/assets/operation_name_collision/mutation.graphql.g.dart
- packages/graphql_codegen/test/assets/operation_name_collision/options.json
- packages/graphql_codegen/test/assets/operation_name_collision/query.graphql
- packages/graphql_codegen/test/assets/operation_name_collision/query.graphql.dart
- packages/graphql_codegen/test/assets/operation_name_collision/query.graphql.g.dart
- packages/graphql_codegen/test/assets/operation_name_collision/schema.graphql
- packages/graphql_codegen/test/assets/operation_name_collision/schema.graphql.dart
> fix: Operation name collision

- packages/graphql_codegen/README.md
> docs: generatedFileHeader option

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/input/input.graphql.dart
- packages/graphql_codegen/test/assets/variables/schema.graphql.dart
- packages/graphql_codegen/test/builder_test.dart
Add missing deep copy functionality to input classes.
> feat: Add deep copy to inputs

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
> release: v0.11.0-beta.2

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/printer/base/json.dart
- packages/graphql_codegen/lib/src/printer/keywords.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/duplicate_names/document.graphql.dart
- packages/graphql_codegen/test/assets/json_converters/document.graphql
- packages/graphql_codegen/test/assets/json_converters/document.graphql.dart
- packages/graphql_codegen/test/assets/json_converters/options.json
- packages/graphql_codegen/test/assets/multiple_interfaces/document.graphql.dart
- packages/graphql_codegen/test/assets/scalars/document.graphql.dart
This PR adds support for `DateTime` serialization and fixes `double` conversion.
> fix: Number and DT converters

- packages/graphql_codegen/test/assets/issue_158/document.graphql
- packages/graphql_codegen/test/assets/issue_158/document.graphql.dart
> repro: Issue #158

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/printer/base/deep_copy.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/issue_160/document.graphql
- packages/graphql_codegen/test/assets/issue_160/document.graphql.dart
> fix: Broken deep copy on nested objects

- packages/graphql_codegen/test/assets/issue_168/payload_test.dart
- packages/graphql_codegen/test/assets/issue_168/schema.graphql
- packages/graphql_codegen/test/assets/issue_168/schema.graphql.dart
> repro: Issue #168

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_switch/example/lib/main.dart
- packages/graphql_switch/example/lib/switch.dart
> release: v0.11.0-beta.6

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
> release: v0.11.0

- packages/graphql_codegen/test/assets/issue_184/document.graphql
- packages/graphql_codegen/test/assets/issue_184/document.graphql.dart
> repro: Issue 184

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/lib/src/printer/base/document.dart
- packages/graphql_codegen/lib/src/printer/context.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/add_typenames/schema.graphql.dart
- packages/graphql_codegen/test/assets/condition_example/fragments.graphql.dart
- packages/graphql_codegen/test/assets/fragments_and_loose_type_requirements/document.graphql.dart
- packages/graphql_codegen/test/assets/fragments_inheritence/document.graphql.dart
- packages/graphql_codegen/test/assets/interface_and_fragments/query.graphql.dart
- packages/graphql_codegen/test/assets/interfaces_and_concrete_types/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_168/schema.graphql.dart
- packages/graphql_codegen/test/assets/issue_192/document.graphql
- packages/graphql_codegen/test/assets/issue_192/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_192/serializer_test.dart
- packages/graphql_codegen/test/assets/lots_of_fragments/document.graphql.dart
- packages/graphql_codegen/test/assets/multiple_interfaces/document.graphql.dart
- packages/graphql_codegen/test/assets/operation_name_collision/mutation.graphql.dart
- packages/graphql_codegen/test/assets/unions/document.graphql.dart
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/lib/src/builder/print.dart
- packages/graphql_switch/pubspec.lock
- packages/graphql_switch/test/assets/initial_test/switch.dart
> repro: Issue 192

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/printer/utils.dart
- packages/graphql_codegen/test/assets/graphql_flutter_naming_config/document.graphql
- packages/graphql_codegen/test/assets/graphql_flutter_naming_config/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_naming_config/options.json
- packages/graphql_codegen/test/assets/naming_config/document.graphql.dart
> fix: Naming separator issue

- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
- packages/graphql_switch/pubspec.yaml
- bump gql: ^0.14.0
- bump gql_code_builder: ^0.6.0
> bump: gql: ^0.14.0 / gql_code_builder: ^0.6.0 FOR analyzer: >=4.0.0 <6.0.0

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
Bump gql and fix naming separator issue.
> release: v0.12.0-beta.1

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/transform/fix_unnamed_operations_visitor.dart
- packages/graphql_codegen/lib/src/transform/transform.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/issue_217/document.graphql
- packages/graphql_codegen/test/assets/issue_217/document.graphql.dart
> feat: Remove unnamed operation definitions before codegen

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
> feat: Upgrade SDK and code-builder version

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/issue_229/graphql/builder_options.json
- packages/graphql_codegen/test/assets/issue_229/graphql/options.json
- packages/graphql_codegen/test/assets/issue_229/graphql/schemaA/document.graphql
- packages/graphql_codegen/test/assets/issue_229/graphql/schemaB/document.graphql
- packages/graphql_codegen/test/assets/issue_229/lib/generated/schemaA/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_229/lib/generated/schemaB/document.graphql.dart
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
> fix: Absolute output dir (windows)

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/lib/src/printer/base/enum.dart
- packages/graphql_codegen/lib/src/visitor/context_visitor.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/extends/document.graphql
- packages/graphql_codegen/test/assets/extends/document.graphql.dart
> feat: Support extend

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/lib/graphql_codegen.dart
- packages/graphql_codegen/lib/src/context.dart
- packages/graphql_codegen/pubspec.yaml
This PR improves performance significantly. It skips unnecessary code generation and caches some lookups.
Thanks to @krishnatejakanchi for raising the issue and providing a testbed for me to debug.
Closes #204
> feat: Improve performance a tad

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.yaml
Further, improve performance by caching schema parsing.
> feat: Cache schema parsing

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
- packages/graphql_switch/pubspec.yaml
> conf: Update deps

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/test/assets/fragment_variables_2/schema.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_naming_config/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_229/lib/generated/schemaA/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_229/lib/generated/schemaB/document.graphql.dart
- packages/graphql_codegen/test/assets/operation_name_collision/query.graphql.dart
> fix: Build errors

- .github/workflows/check_pr.yml
- .github/workflows/publish.yml
- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/lib/main.graphql.dart
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/lib/src/printer/clients/graphql.dart
- packages/graphql_codegen/lib/src/printer/clients/utils.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/fragment_variables_2/schema.graphql.dart
- packages/graphql_codegen/test/assets/graphql_client/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_mutation_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_no_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_optional_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_client_query_required_arguments/document.graphql.dart
- packages/graphql_codegen/test/assets/graphql_flutter_naming_config/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_229/lib/generated/schemaA/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_229/lib/generated/schemaB/document.graphql.dart
- packages/graphql_codegen/test/assets/operation_name_collision/mutation.graphql.dart
- packages/graphql_codegen/test/assets/operation_name_collision/query.graphql.dart
- packages/graphql_codegen/test/builder_test.dart
> fix: onComplete

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/src/config/config.dart
- packages/graphql_codegen/lib/src/config/config.g.dart
- packages/graphql_codegen/lib/src/printer/base/enum.dart
- packages/graphql_codegen/lib/src/printer/base/json.dart
- packages/graphql_codegen/lib/src/printer/base/property.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/enum_custom_fallback/document.graphql
- packages/graphql_codegen/test/assets/enum_custom_fallback/document.graphql.dart
- packages/graphql_codegen/test/assets/enum_custom_fallback/options.json
> feat: Support custom enum fallback values

- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
- packages/graphql_switch/pubspec.yaml
> feat(graphql_codegen): bump gql to ^1.0.0

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/pubspec.yaml
> release: v0.13.0

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/src/context/context.dart
- packages/graphql_codegen/lib/src/printer/base/deprecation.dart
- packages/graphql_codegen/lib/src/printer/base/enum.dart
- packages/graphql_codegen/lib/src/printer/base/property.dart
- packages/graphql_codegen/lib/src/visitor/context_visitor.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/deprecated/document.graphql
- packages/graphql_codegen/test/assets/deprecated/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_179/schema.graphql.dart
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
- packages/graphql_switch/test/assets/initial_test/switch.dart
> feat: Support deprecated directive

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/src/context/context.dart
- packages/graphql_codegen/lib/src/printer/base/input.dart
- packages/graphql_codegen/lib/src/printer/base/property.dart
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/issue_293/document.graphql
- packages/graphql_codegen/test/assets/issue_293/document.graphql.dart
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
> feat: Support non-nullable input with default value

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/src/printer/base/equality.dart
- packages/graphql_codegen/lib/src/printer/base/input.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/issue_293/doc_test.dart
- packages/graphql_codegen/test/assets/issue_293/document.graphql
- packages/graphql_codegen/test/assets/issue_293/document.graphql.dart
> Fix poor handling of complex types

- packages/graphql_codegen/lib/src/printer/base/equality.dart
- packages/graphql_codegen/lib/src/printer/base/input.dart
- packages/graphql_codegen/lib/src/printer/base/json.dart
- packages/graphql_codegen/lib/src/printer/utils.dart
- packages/graphql_codegen/test/assets/issue_293/doc_test.dart
- packages/graphql_codegen/test/assets/issue_293/document.graphql.dart
> ref: Default value code

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
> release: v0.13.5

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/lib/builder.dart
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_codegen/test/assets/issue_318/builder_options.json
- packages/graphql_codegen/test/assets/issue_318/graphql/query1/q.graphql
- packages/graphql_codegen/test/assets/issue_318/graphql/query2/q.graphql
- packages/graphql_codegen/test/assets/issue_318/graphql/schema.graphql
- packages/graphql_codegen/test/assets/issue_318/lib/query1/q.graphql.dart
- packages/graphql_codegen/test/assets/issue_318/lib/query2/q.graphql.dart
- packages/graphql_codegen/test/assets/issue_318/lib/schema.graphql.dart
- packages/graphql_codegen/test/assets/issue_318/options.json
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
> fix: Issue 318

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
- packages/graphql_switch/example/pubspec.lock
- packages/graphql_switch/pubspec.lock
> release: v0.13.9

- packages/graphql_codegen/test/assets/issue_348/document.graphql
- packages/graphql_codegen/test/assets/issue_348/document.graphql.dart
- packages/graphql_codegen/test/assets/issue_348/options.json
- packages/graphql_codegen/test/assets/issue_348/scalar_import.dart
- packages/graphql_codegen/test/assets/scalars/options.json
Add test for custom date time parsing.
> feat: Add custom scalar parsing

- packages/graphql_codegen/lib/src/context/context.dart
- packages/graphql_codegen/lib/src/printer/base/input.dart
- packages/graphql_codegen/lib/src/printer/base/property.dart
- packages/graphql_codegen/test/assets/input_oneOf/input.graphql
- packages/graphql_codegen/test/assets/input_oneOf/input.graphql.dart
- packages/graphql_codegen/test/assets/input_oneOf/options.json
> feat: Support @oneOf

- packages/graphql_codegen/CHANGELOG.md
- packages/graphql_codegen/example/pubspec.lock
- packages/graphql_codegen/example/pubspec.yaml
- packages/graphql_codegen/pubspec.lock
- packages/graphql_codegen/pubspec.yaml
> feat: Upgrade gql_code_builder
